<?php

$data = $block->getUserData()->getData();

?>
    <table class="table table-dark">
        <tr>
            <th><?php echo __('Login Id') ?></th>
            <th><?php echo __('Email') ?></th>
            <th><?php echo __('Login Time') ?></th>
            <th><?php echo __('Logout Time') ?></th>
        </tr>
<?php
     foreach($data as $data)
{
?>
        <tr>
            <td><?= $data['test_id'];?></td>
            <td><?= $data['title'];?></td>
            <td><?= $data['creation_time'];?></td>
            <td><?= $data['checkout_time'];?></td>
        </tr>   
<?php
}
?>
    </table>
   
<?php if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif ?>

<style>
.limiter
{
    float: left;
    margin-left: 20px;
}
.items
{
    float:right;
}
</style>